/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-06-10 08:49:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/web_0226_lyh/worksapce/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/layout/header.jsp", Long.valueOf(1749526252376L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1748490521246L));
    _jspx_dependants.put("/WEB-INF/views/layout/footer.jsp", Long.valueOf(1749533971189L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Spring Project</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-body-tertiary\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<nav class=\"navbar bg-body-tertiary\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a class=\"navbar-brand\" href=\"/\">\r\n");
      out.write("						<img src=\"/resources/image/logo.jpg\" alt=\"Bootstrap\" width=\"50\" height=\"50\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<button class=\"navbar-toggler\"\r\n");
      out.write("				type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\"\r\n");
      out.write("				data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("				aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/board/register\">Board Register</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/board/list\">Board List</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/user/register\">Join</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/user/login\">Login</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"w-25 position-absolute top-50 start-50 translate-middle p-5 border rounded\"\r\n");
      out.write("	style=\"background-color: azure;\">\r\n");
      out.write("	<form action=\"/user/register\" method=\"post\">\r\n");
      out.write("		<h3 class=\"text-center\">User Join Page</h3>\r\n");
      out.write("		<div class=\"mt-4 mb-3 row align-items-center\">\r\n");
      out.write("			<div class=\"col-12\" id=\"feedback\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3 row align-items-center\">\r\n");
      out.write("			<div class=\"col-4\">Email address</div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<input type=\"text\"\r\n");
      out.write("					class=\"form-control\"\r\n");
      out.write("					id=\"email\"\r\n");
      out.write("					name=\"email\"\r\n");
      out.write("					placeholder=\"name@example.com\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3 row align-items-center\">\r\n");
      out.write("			<div class=\"col-4\">\r\n");
      out.write("				<button type=\"button\" id=\"emailCheckBtn\" class=\"btn btn-secondary\">중복 체크</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-8\" id=\"emailCheckStmt\">이메일 중복 체크를 해주세요.</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"mb-3 row align-items-center\">\r\n");
      out.write("			<div class=\"col-4\">Nickname</div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<input type=\"text\"\r\n");
      out.write("					class=\"form-control\"\r\n");
      out.write("					id=\"nickName\"\r\n");
      out.write("					name=\"nickName\"\r\n");
      out.write("					placeholder=\"Nickname\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"mb-3 row align-items-center\">\r\n");
      out.write("			<div class=\"col-4\">Password</div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<input type=\"text\"\r\n");
      out.write("					class=\"form-control\"\r\n");
      out.write("					id=\"pwd\"\r\n");
      out.write("					name=\"pwd\"\r\n");
      out.write("					placeholder=\"password\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3 row align-items-center\">\r\n");
      out.write("			<div class=\"col-4\">Check</div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<input type=\"password\"\r\n");
      out.write("					class=\"form-control\"\r\n");
      out.write("					id=\"pwdCheck\"\r\n");
      out.write("					placeholder=\"Check\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">비밀번호는 영문 대문자, 소문자, 숫자를 각각 포함하고 8자 이상이어야 합니다.</div>\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-primary w-100\">JOIN</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/userRegister.js\"></script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"position-absolute start-50 top-100 pb-3\"\r\n");
      out.write("	style=\"transform: translate(-50%, -100%);\">2025 Spring Project... by 이유현</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
