/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-06-09 01:31:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/layout/header.jsp", Long.valueOf(1748996056698L));
    _jspx_dependants.put("/WEB-INF/views/layout/footer.jsp", Long.valueOf(1749020474443L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Spring Project</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-body-tertiary\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<nav class=\"navbar bg-body-tertiary\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a class=\"navbar-brand\" href=\"/\"> <img src=\"/resources/image/logo.jpg\" alt=\"Bootstrap\" width=\"50\" height=\"50\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"\r\n");
      out.write("			>\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/board/register\">Board Register</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/board/list\">Board List</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-md\">\r\n");
      out.write("	<h3>Board Register Page</h3>\r\n");
      out.write("\r\n");
      out.write("	<!-- enctype : multipart/form-data -->\r\n");
      out.write("	<form action=\"/board/insert\"\r\n");
      out.write("		method=\"post\"\r\n");
      out.write("		enctype=\"multipart/form-data\">\r\n");
      out.write("		<!-- bvo area -->\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label for=\"title\" class=\"form-label\">Title</label>\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"form-control\"\r\n");
      out.write("				id=\"title\"\r\n");
      out.write("				placeholder=\"Title\"\r\n");
      out.write("				name=\"title\"\r\n");
      out.write("				required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label for=\"writer\" class=\"form-label\">Writer</label>\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"form-control\"\r\n");
      out.write("				id=\"writer\"\r\n");
      out.write("				placeholder=\"writer\"\r\n");
      out.write("				name=\"writer\"\r\n");
      out.write("				required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label for=\"content\" class=\"form-label\">Content</label>\r\n");
      out.write("			<textarea class=\"form-control\"\r\n");
      out.write("				id=\"content\"\r\n");
      out.write("				rows=\"5\"\r\n");
      out.write("				name=\"content\"\r\n");
      out.write("				required></textarea>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- file add area -->\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<input type=\"file\"\r\n");
      out.write("				class=\"form-control\"\r\n");
      out.write("				id=\"file\"\r\n");
      out.write("				name=\"files\"\r\n");
      out.write("				multiple\r\n");
      out.write("				style=\"display: none\">\r\n");
      out.write("			<button type=\"button\"\r\n");
      out.write("				class=\"btn btn-outline-primary\"\r\n");
      out.write("				id=\"trigger\">Upload files</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- file list area -->\r\n");
      out.write("		<div class=\"mb-3\" id=\"fileZone\"></div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- button -->\r\n");
      out.write("		<button type=\"submit\" class=\"btn btn-success\" id=\"regBtn\">등록</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/boardRegisterFile.js\"></script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-md d-flex justify-content-center\">2025 Spring Project... by 이유현</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
